Add restart file integrity check. Improve test run directory setup.

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -21,6 +21,7 @@ help:
 	@echo "make test_rundir      - create run directory 'run/'"
 	@echo "make test_run NP=3    - cd run; mpiexec -n 3 ipe.x"
 	@echo "make test_check       - check test results"
+	@echo "make check_restartfile - verify restart file integrity"
 	@echo "make clean            - remove files created by test"
 
 test:
@@ -36,10 +37,37 @@ test:
 test_compile:
 	cd ..; make -j; make install
 
+RESTARTFILE = IPE_State.apex.201303160000.nc
+md5ref = 951f6543479fe3aecb8c49ea2d318190
+
+check_restartfile:
+	@cd run && \
+	if [ ! -f $(RESTARTFILE) ]; then echo "Error: $(RESTARTFILE) not found"; exit 1; fi; \
+	if command -v md5sum >/dev/null 2>&1; then \
+	  md5code=`md5sum $(RESTARTFILE) | cut -d ' ' -f 1`; \
+	elif command -v md5 >/dev/null 2>&1; then \
+	  md5code=`md5 -q $(RESTARTFILE)`; \
+	else \
+	  echo "Error: Neither md5sum nor md5 found"; exit 1; \
+	fi; \
+	if [ "$$md5code" = "$(md5ref)" ]; then \
+	  echo "$(RESTARTFILE) is the right file for restart."; \
+	else \
+	  echo "Warning: $(RESTARTFILE) MD5 mismatch! This is not the correct file for restart!"; exit 1; \
+	fi
+
 test_rundir:
 	rm -rf run
 	mkdir -p run
-	cd run; ln -s ../../install/bin/ipe.x .
+	cd run && ln -s ../../install/bin/ipe.x . && \
+	if [ -d ../data ]; then \
+	  cp -f ../data/IPE.inp .; \
+	  ln -s ../data/ionprof .; \
+	  ln -s ../data/tiros_spectra .; \
+	  ln -s ../data/IPE_Grid.nc .; \
+	  ln -s ../data/IPE_State.apex.201303160000_AFTER.v3_fixed.nc IPE_State.apex.201303160000.nc; \
+	  ln -s ../data/global_idea_coeff_W05* .; \
+	fi
 
 # Needed for hot restart only
 #	cd run; ln -s ../data/* .
@@ -51,6 +79,7 @@ test_run:
 	cd run;	mpiexec -n $(NP) ./ipe.x > runlog
 
 test_check:
+	$(MAKE) check_restartfile
 	scripts/compare_sums.py run/$(TESTFILE) reference.txt \
 	> test.diff
 	@cat test.diff
